"""Suspicious API key usage detection rule."""

from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, List

from sqlalchemy import and_
from sqlalchemy.orm import Session

from ...models import Event
from .base import DetectionRule


class SuspiciousApiKeyRule(DetectionRule):
    """
    Detect suspicious API key generation activity.

    Triggers when:
    - GenerateAccessKey action occurs outside of business hours (08:00-18:00 UTC)
    - Indicates potential unauthorized activity or compromised service accounts

    MITRE ATT&CK: T1078.004 (Valid Accounts: Cloud Accounts)
    """

    @property
    def rule_id(self) -> str:
        return "suspicious_api_key"

    @property
    def name(self) -> str:
        return "Suspicious API Key Generation"

    @property
    def description(self) -> str:
        return "Detects API key generation outside of standard business hours"

    @property
    def severity(self) -> str:
        return "medium"

    @property
    def window_minutes(self) -> int:
        return 60  # 1-hour window

    def detect(
        self, db: Session, window_start: datetime, window_end: datetime
    ) -> List[Dict[str, Any]]:
        """Detect API key generation outside business hours."""
        events = (
            db.query(Event)
            .filter(
                and_(
                    Event.timestamp >= window_start,
                    Event.timestamp <= window_end,
                    Event.action == "GenerateAccessKey",
                )
            )
            .all()
        )

        alerts = []
        for event in events:
            # Check if event time is outside 08:00 - 18:00 UTC
            hour = event.timestamp.hour
            if hour < 8 or hour >= 18:
                evidence = {
                    "user": event.actor,
                    "action": event.action,
                    "timestamp": event.timestamp.isoformat(),
                    "source_ip": event.source_ip,
                    "region": event.raw_data.get("region") if event.raw_data else None,
                    "event_id": event.id,
                }

                alerts.append(
                    {
                        "rule_id": self.rule_id,
                        "severity": self.severity,
                        "summary": f"Suspicious API key generated by {event.actor} at {event.timestamp.isoformat()} (Outside business hours)",
                        "evidence": evidence,
                        "alert_time": window_end,
                        "window_start": window_start,
                        "window_end": window_end,
                    }
                )

        return alerts
