"""SQLAlchemy data models for SignalForge."""

from datetime import datetime
from enum import Enum

from sqlalchemy import JSON, Column, DateTime, Integer, String, Text
from sqlalchemy.sql import func

from .database import Base


class AlertStatus(str, Enum):
    """Alert status enumeration."""

    OPEN = "open"
    TRIAGED = "triaged"
    CLOSED = "closed"
    FALSE_POSITIVE = "false_positive"


class AlertSeverity(str, Enum):
    """Alert severity levels."""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class Event(Base):
    """Canonical event schema for all ingested security events."""

    __tablename__ = "events"

    id = Column(Integer, primary_key=True, index=True)
    timestamp = Column(DateTime, nullable=False, index=True)
    actor = Column(String(255), nullable=True, index=True)
    source_ip = Column(String(45), nullable=True, index=True)  # IPv6 max length
    user_agent = Column(Text, nullable=True)
    action = Column(String(255), nullable=False, index=True)
    resource = Column(String(512), nullable=True)
    outcome = Column(String(50), nullable=True, index=True)  # success, failure, error
    request_id = Column(String(255), nullable=True, index=True)
    raw_data = Column(JSON, nullable=True)  # Store original event for forensics
    created_at = Column(DateTime, server_default=func.now(), nullable=False)


class Alert(Base):
    """Security alert generated by detection rules."""

    __tablename__ = "alerts"

    id = Column(Integer, primary_key=True, index=True)
    rule_id = Column(String(100), nullable=False, index=True)
    severity = Column(String(20), nullable=False, index=True)
    status = Column(String(20), nullable=False, default=AlertStatus.OPEN.value, index=True)
    summary = Column(Text, nullable=False)
    evidence = Column(JSON, nullable=False)  # Stores event IDs, counts, time windows
    alert_time = Column(DateTime, nullable=False, index=True)
    window_start = Column(DateTime, nullable=True)
    window_end = Column(DateTime, nullable=True)
    created_at = Column(DateTime, server_default=func.now(), nullable=False)
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now(), nullable=False)


class AllowlistEntry(Base):
    """IP or actor allowlist for suppressing false positives."""

    __tablename__ = "allowlist"

    id = Column(Integer, primary_key=True, index=True)
    entry_type = Column(String(20), nullable=False, index=True)  # 'ip' or 'actor'
    entry_value = Column(String(255), nullable=False, index=True)
    reason = Column(Text, nullable=False)
    rule_id = Column(String(100), nullable=True)  # Optional: allowlist for specific rule only
    expires_at = Column(DateTime, nullable=True, index=True)
    created_by = Column(String(255), nullable=True)
    created_at = Column(DateTime, server_default=func.now(), nullable=False)


class FalsePositive(Base):
    """Track false positive alerts with reason for tuning."""

    __tablename__ = "false_positives"

    id = Column(Integer, primary_key=True, index=True)
    alert_id = Column(Integer, nullable=False, index=True)
    reason = Column(Text, nullable=False)
    marked_by = Column(String(255), nullable=True)
    marked_at = Column(DateTime, server_default=func.now(), nullable=False)
